# make all
glob:
	@cd Q1 && make
	@cd Q2 && make
	@cd Q3 && make
	@cd Q4 && make

# make run for each question
run-Q1:
	@cd Q1 && make run --no-print-directory

run-Q2:
	@cd Q2 && make run --no-print-directory

run-Q3:
	@cd Q3 && make run --no-print-directory

run-Q4:
	@cd Q4 && make run --no-print-directory

# make out for each question
out-Q1:
	@cd Q1 && make out --no-print-directory

out-Q2:
	@cd Q2 && make out --no-print-directory

out-Q3:
	@cd Q3 && make out --no-print-directory

out-Q4:
	@cd Q4 && make out --no-print-directory

# make clean all
clean:
	@cd Q1 && make clean
	@cd Q2 && make clean
	@cd Q3 && make clean
	@cd Q4 && make clean
