# make all
glob:
	@cd Q1 && make
	@cd Q2 && make

# make run for each question
run-Q1:
	@cd Q1 && make run --no-print-directory

run-Q2:
	@cd Q2 && make run --no-print-directory

# make clean all
clean:
	@cd Q1 && make clean
	@cd Q2 && make clean
